package com.github.observeroftime.gregtechweebified.adders;

import gregtech.GT_Mod;
import gregtech.api.enums.ItemList;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.util.GT_OreDictUnificator;

import static com.github.observeroftime.gregtechweebified.adders.MaterialAdder.*;


public class FluidAdder implements Runnable {
    @Override
    public void run() {
        GT_Mod.gregtechproxy.addFluid("liquid.gamergirlbathwater", "molten.autogenerated", "Gamergirl Bathwater", Gamergirlbathwater, Gamergirlbathwater.mRGBa, 1, 305, GT_OreDictUnificator.get(OrePrefixes.cell, Gamergirlbathwater, 1L), ItemList.Cell_Empty.get(1L, new Object[0]), 1000);
    }
}
